// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1580365109);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 5);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "TR");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200110142707");
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"1fd967a2-2c79-46a3-90c2-44ca2f631c18\",\"default-theme@mozilla.org\":\"3569ac8b-6bf1-46de-95b4-7815684623ad\",\"google@search.mozilla.org\":\"86c3845a-7e5c-4ef9-b81e-85aae9394802\",\"amazondotcom@search.mozilla.org\":\"e77161e2-1fb7-4c2d-a1b2-ff5727aabd40\",\"bing@search.mozilla.org\":\"edae32a0-bd74-4112-9c72-ddf1cff95d97\",\"ddg@search.mozilla.org\":\"e51e5bdd-a3ec-49a1-868b-581c61a72965\",\"twitter@search.mozilla.org\":\"e23fa5bc-2a9e-4711-be58-21556eba7ca2\",\"wikipedia@search.mozilla.org\":\"62236ed2-0a1d-4988-8ef0-f8943ecfafd0\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "03c4d825-e238-4ab1-ac78-e6c1ee85c1b");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.4.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "08659d36-7ef4-4d41-b55c-9b0846be82a9");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.prompted", 2);
